import Head from "next/head";
import Image from "next/image";
import { panchang } from "./_app";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sunsets & Prosecco</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex h-[90vh] items-center justify-center text-center text-white">
          <div className="absolute top-0 left-0 z-[1] h-full w-full bg-slate-400">
            <video
              className="h-full w-full object-cover "
              playsInline
              preload="auto"
              autoPlay
              muted
              loop
            >
              <source src="/sunsets.mp4" type="video/mp4" />
            </video>
          </div>
          <div className="z-10">
            <h1
              className={`${panchang.className} ml-24 text-3xl uppercase leading-none`}
            >
              Sunsets &
            </h1>
            <h1 className="font-serif text-8xl leading-none">Prosecco</h1>
          </div>
        </div>
        <div className="bg-[#EFBCBF] py-12 px-4">
          <div className="mx-auto max-w-xl text-center text-lg font-medium leading-snug text-[#BA4A4A]">
            <p className="mb-8">
              Join us for birthday + housewarming shenanigans. We are combining
              two of our favourite things: Sunsets and Prosecco!🌅🍾{" "}
            </p>
            <p>
              To set the mood, we&lsquo;re going for a Sunset Chic dress code.
              Think flowy fabrics in warm sunset hues like burnt orange, dusty
              pink, and golden yellow. Lets create a picture-perfect scene
              together! 🎞
            </p>
          </div>
        </div>
        <div className="py-12 px-4">
          <div className="mx-auto grid max-w-xl grid-cols-2 gap-4">
            <Button title="RSVP Now" />
            <Button title="Fashion Inspo" />
            <Button title="Get Directions" />
            <Button title="Add to Playlist" />
          </div>
          <div className="mx-auto grid max-w-xl grid-cols-2 gap-y-8 gap-x-2 py-12 text-center">
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/time.svg" fill alt="time" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                5pm - 1am
              </p>
            </div>
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/invite.svg" fill alt="invite" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                invite only
              </p>
            </div>
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/food.svg" fill alt="food" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                food and snacks available
              </p>
            </div>
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/sunset.svg" fill alt="sunset" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                sunset view (6:15pm)
              </p>
            </div>
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/dress.svg" fill alt="dress" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                dresscode: sunset chic
              </p>
            </div>
            <div className="flex flex-col items-center justify-start">
              <div className="relative mb-2 flex h-16 w-16 flex-col items-center justify-start">
                <Image src="/bottle.svg" fill alt="bottle" />
              </div>
              <p className="text-md max-w-[12ch] font-bold leading-tight">
                bring 1 bottle prosecco
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  title: string;
}

const Button = (props: ButtonProps) => {
  return (
    <div className="relative w-full">
      <button
        className="w-full whitespace-nowrap rounded-lg border-4 border-[#FB9062] bg-white px-8 py-4 text-center text-xs font-bold uppercase"
        {...props}
      >
        {props.title}
      </button>
      <button
        className="absolute top-1 left-1 z-[-1] w-full whitespace-nowrap rounded-lg border-4 border-[#0F0F0F] bg-[#0F0F0F] px-8 py-4 text-center text-xs font-bold uppercase"
        disabled
      >
        {props.title}
      </button>
    </div>
  );
};
